kafka:
  brokers: ["redpanda:9092"]
  
redpanda:
  adminApi:
    enabled: true
    urls: ["http://redpanda:9644"]

schemaRegistry:
  enabled: true
  urls: ["http://redpanda:8081"]

server:
  listenPort: 8080
